### ISSUE TITLE
Inventory doesnt ajust to camera.

### ISSUE THREAD

**Issue by RealDraymaHours** [RealDraymaHours/ProjectBAW#1]
Currently the inventory screen has a fixed size. If I zoom in or out then the inventory doesnt ajust to the camera and just zooms in or out with the camera. The basic solution would be to calculate the difference and use the base as a start. That wont work because the buttons on the inventory are also fixed.
![Naamloos](https://user-images.githubusercontent.com/91953640/200141969-555196a3-c0a4-4db4-9189-11c529bdac3e.png)

**Comment by Fontie** [comment]
Solution could be to have the current camera mode saved in the inventory and then insta zoom into the inv position when opened. Then insta jump back into the old camera mode.
